version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Install phase"

  build:
    commands:
      - echo "Zipping Lambda function"
      - zip -r function.zip index.js

  post_build:
    commands:
      - echo "Deploying to Lambda"
      - aws lambda update-function-code \
          --function-name lambda-codebuild-demo \
          --zip-file fileb://function.zip
